name: TPHistory
version: '${version}'
main: com.trickypr.tpHistory.TPHistory
api-version: 1.19

commands:
  tphist:
    description: Find the teleportation history for a player
    usage: /tphist player <username>, ej /tphist player Gwentym
    permission: tphistory.tphist.player