name: TPHistory
version: 1.0
description: Este Plugin es para darle seguimiento a los teletransportes.
author: TwentyHeavens
main: com.trickypr.tpHistory.TeleportTracerPlugin
api-version: 1.21

commands:
  tphist:
    description: Comandos para el historial de teletransportaciones.
    usage: /<command> [player] [page]
    aliases: [tph]
    permission: tphistory.command.use # Permiso general para usar el comando base
    permission-message: No tienes permiso para usar este comando.

permissions:
  tphistory.command.use:
    description: Permite usar el comando tphist y sus aliases.
    default: true # Considera 'op' si prefieres que solo los OPs puedan usarlo por defecto.
  tphistory.command.reload:
    description: Permite recargar la configuración del plugin.
    default: op # Solo operadores deberían poder recargar la configuración.
  tphistory.command.listplayers:
    description: Permite ver el historial de teletransportaciones de otros jugadores.
    default: op # Solo operadores deberían poder ver el historial de otros por defecto.
    children:
      tphistory.command.playerpages: true # Permiso implícito si tienen listplayers
                                          # Si quieres que 'playerpages' sea independiente, elimia esta línea.
  tphistory.command.playerpages:
    description: Permite especificar una página al ver el historial de otros jugadores.
    default: op # Recomendado 'op'. Si un usuario tiene 'tphistory.command.listplayers'
                # pero no este, solo podrá ver la primera página del historial de otros.
                # NOTA: Si está como 'children' arriba, este 'default' es menos relevante.